source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DZMemo_Example', :exclusive => true do
  pod "DZMemo", :path => "../"
end

target 'DZMemo_Tests', :exclusive => true do
  pod "DZMemo", :path => "../"

  pod 'Kiwi'
end
